export const RIOMIND_AGENTS = [
  "research",
  "business",
  "developer",
  "education",
  "science",
  "legal",
  "medical",
  "finance",
  "trading",
  "blockchain",
  "governance",
  "treasury",
  "marketing",
  "creator",
  "project_manager",
  "operations",
  "security",
  "data_science",
  "cloud",
  "telecom",
  "enterprise",
] as const;
