export type PrimeAiCodebasePackage = {
  nicheId: string;
  packageName: string;
  maturity: "blueprint" | "scaffold_ready" | "runtime_pending" | "runtime_ready";
  scaffoldPath?: string;
  runtimeUrl?: string;
  productSurface: string;
  frontendSurfaces: string[];
  backendServices: string[];
  databaseModels: string[];
  runtimeWorkers: string[];
  rioMindNexusIntegrations: string[];
  creatorUtilityModules: string[];
  complianceNotes: string[];
};

const GENERIC_AI_CODEBASE: PrimeAiCodebasePackage = {
  nicheId: "generic_ai_prime_project",
  packageName: "Generic Prime AI Codebase Package",
  maturity: "scaffold_ready",
  productSurface: "Generic AI project surface",
  frontendSurfaces: [
    "Project landing page",
    "Creator dashboard",
    "User workspace",
    "Analytics surface",
  ],
  backendServices: [
    "Project profile service",
    "Utility module service",
    "Usage tracking service",
    "Metadata proof service",
  ],
  databaseModels: [
    "prime_ai_projects",
    "prime_ai_modules",
    "prime_ai_usage_events",
    "prime_ai_activity_logs",
  ],
  runtimeWorkers: [
    "AI task queue worker",
    "Usage aggregation worker",
    "Project summary worker",
  ],
  rioMindNexusIntegrations: [
    "Project context registration",
    "Creator assistant",
    "Utility recommendation engine",
  ],
  creatorUtilityModules: [
    "Project website",
    "Documentation pack",
    "Analytics dashboard",
  ],
  complianceNotes: [
    "AI output review required.",
    "Creator remains responsible for public project claims.",
  ],
};

const PACKAGES: Record<string, PrimeAiCodebasePackage> = {
  blockchain_ai: {
    nicheId: "blockchain_ai",
    packageName: "Blockchain AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Smart-contract, tokenomics, DEX, bridge, validator, governance, and on-chain intelligence.",
    frontendSurfaces: ["Chain intelligence dashboard", "Smart contract analyzer", "Tokenomics simulator", "DEX liquidity risk panel", "Governance review surface"],
    backendServices: ["Contract parser service", "On-chain proof service", "Liquidity analyzer", "Bridge risk service", "Governance intelligence service"],
    databaseModels: ["blockchain_ai_projects", "contract_reviews", "tokenomics_models", "liquidity_risk_reports", "governance_reviews"],
    runtimeWorkers: ["contract_analysis_worker", "tokenomics_simulation_worker", "dex_risk_worker", "bridge_risk_worker"],
    rioMindNexusIntegrations: ["Smart contract explainer", "Tokenomics analyst", "On-chain proof assistant", "Governance proposal reviewer"],
    creatorUtilityModules: ["Explorer proof layer", "Developer portal", "Risk report generator", "Analytics dashboard"],
    complianceNotes: ["Smart-contract review is not an audit guarantee.", "Bridge and liquidity risks require professional review."],
  },
  cloud_ai: {
    nicheId: "cloud_ai",
    packageName: "Cloud AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Cloud architecture, scaling, DevOps, observability, security, cost, and disaster recovery intelligence.",
    frontendSurfaces: ["Cloud architecture planner", "Scaling simulator", "Cost dashboard", "Observability map", "Incident response workspace"],
    backendServices: ["Infrastructure planner", "Cost analyzer", "CI/CD registry", "Security checklist service", "Monitoring adapter"],
    databaseModels: ["cloud_projects", "cloud_architectures", "deployment_plans", "cost_estimates", "incident_reports"],
    runtimeWorkers: ["cost_optimization_worker", "scaling_analysis_worker", "security_review_worker"],
    rioMindNexusIntegrations: ["Cloud architect assistant", "DevOps copilot", "Incident analysis assistant", "Cost optimization analyst"],
    creatorUtilityModules: ["Documentation pack", "Analytics dashboard", "Developer portal", "Security review layer"],
    complianceNotes: ["Cloud estimates are not guarantees.", "Production deployment requires security review."],
  },
  telecom_ai: {
    nicheId: "telecom_ai",
    packageName: "Telecom AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Network planning, coverage, bandwidth, edge, subscriber analytics, and service quality intelligence.",
    frontendSurfaces: ["Network planning console", "Coverage map", "Bandwidth analyzer", "Subscriber analytics", "QoS monitor"],
    backendServices: ["Network model service", "Telemetry adapter", "Subscriber analytics engine", "QoS monitor", "Edge node registry"],
    databaseModels: ["telecom_networks", "coverage_models", "bandwidth_reports", "subscriber_segments", "qos_events"],
    runtimeWorkers: ["coverage_model_worker", "qos_analysis_worker", "bandwidth_forecast_worker"],
    rioMindNexusIntegrations: ["Network planning assistant", "Coverage analyst", "QoS explanation assistant", "Edge optimization advisor"],
    creatorUtilityModules: ["Analytics dashboard", "Verification layer", "Documentation pack", "Operations console"],
    complianceNotes: ["Coverage models require field validation.", "Telecom deployment may require regulatory approval."],
  },
  data_science_machine_learning_ai: {
    nicheId: "data_science_machine_learning_ai",
    packageName: "Data Science & Machine Learning AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Dataset profiling, feature engineering, model selection, evaluation, bias, drift, and ML deployment planning.",
    frontendSurfaces: ["Dataset profiler", "Feature engineering studio", "Model experiment tracker", "Metrics dashboard", "Prediction workspace"],
    backendServices: ["Dataset ingestion service", "Feature pipeline", "Model registry", "Metrics evaluator", "Drift detector"],
    databaseModels: ["ml_projects", "datasets", "feature_sets", "model_experiments", "evaluation_metrics", "drift_reports"],
    runtimeWorkers: ["feature_engineering_worker", "model_evaluation_worker", "bias_detection_worker", "drift_monitor_worker"],
    rioMindNexusIntegrations: ["Data science analyst", "Feature engineering assistant", "Model selection advisor", "Metrics explainer"],
    creatorUtilityModules: ["Analytics dashboard", "Dataset marketplace", "Developer portal", "Report generator"],
    complianceNotes: ["Model predictions are uncertain.", "Bias, drift, and data quality must be reviewed."],
  },
  legal_ai: {
    nicheId: "legal_ai",
    packageName: "Legal AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Contract review, clause extraction, legal risk flags, compliance checklists, and document comparison.",
    frontendSurfaces: ["Legal document workspace", "Contract summary panel", "Clause risk map", "Compliance checklist", "Document comparison viewer"],
    backendServices: ["Document parser", "Clause extraction service", "Risk classifier", "Compliance checklist engine", "Jurisdiction metadata service"],
    databaseModels: ["legal_projects", "legal_documents", "contract_clauses", "legal_risk_flags", "compliance_reviews"],
    runtimeWorkers: ["legal_document_parser_worker", "clause_extraction_worker", "risk_flag_worker"],
    rioMindNexusIntegrations: ["Contract summary assistant", "Clause risk assistant", "Compliance checklist assistant", "Legal research organizer"],
    creatorUtilityModules: ["Documentation pack", "Verification layer", "Review handoff", "Analytics dashboard"],
    complianceNotes: ["Not legal advice.", "A qualified lawyer must review legal outputs."],
  },
  medical_ai: {
    nicheId: "medical_ai",
    packageName: "Medical AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Medical literature, patient education, clinical workflow support, compliance, and health research assistance.",
    frontendSurfaces: ["Medical research portal", "Literature summary workspace", "Patient education panel", "Consent workflow", "Safety-first assistant"],
    backendServices: ["Literature parser", "Health workflow service", "Consent record service", "Compliance review service", "Data access audit"],
    databaseModels: ["medical_projects", "medical_literature", "health_workflows", "consent_records", "medical_compliance_reviews"],
    runtimeWorkers: ["medical_literature_worker", "health_summary_worker", "compliance_check_worker"],
    rioMindNexusIntegrations: ["Medical literature assistant", "Patient education assistant", "Compliance checklist assistant", "Safety explanation assistant"],
    creatorUtilityModules: ["Verification layer", "Documentation pack", "Research portal", "Analytics dashboard"],
    complianceNotes: ["Not medical advice.", "No diagnosis guarantee. Doctor review is required."],
  },
  complex_project_manager_ai: {
    nicheId: "complex_project_manager_ai",
    packageName: "Complex Project Manager AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Milestones, dependencies, budgets, teams, risks, decision logs, and executive project reporting.",
    frontendSurfaces: ["Project command center", "Milestone planner", "Dependency map", "Risk register", "Budget tracker", "Decision log"],
    backendServices: ["Project planning service", "Dependency engine", "Risk scoring service", "Budget tracker", "Report generator"],
    databaseModels: ["complex_projects", "project_milestones", "project_dependencies", "project_risks", "project_budgets", "decision_logs"],
    runtimeWorkers: ["dependency_analysis_worker", "risk_scoring_worker", "progress_report_worker"],
    rioMindNexusIntegrations: ["Project strategist", "Risk analyst", "Milestone planner", "Executive report assistant"],
    creatorUtilityModules: ["Analytics dashboard", "Documentation pack", "Telegram utility", "Execution console"],
    complianceNotes: ["Project plans require human management.", "Budget and timelines are estimates."],
  },
  code_software_developer_ai: {
    nicheId: "code_software_developer_ai",
    packageName: "Code & Software Developer AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Architecture, coding, debugging, testing, security review, DevOps, and software engineering copilot.",
    frontendSurfaces: ["Developer copilot workspace", "Code review panel", "Architecture planner", "Debugging console", "Test generator", "Deployment assistant"],
    backendServices: ["Code analysis service", "Refactor planner", "Test generator", "Dependency scanner", "Security checklist service"],
    databaseModels: ["software_projects", "code_reviews", "debug_sessions", "test_plans", "security_findings", "deployment_reviews"],
    runtimeWorkers: ["code_analysis_worker", "test_generation_worker", "security_scan_worker", "refactor_plan_worker"],
    rioMindNexusIntegrations: ["Software architect assistant", "Debugging copilot", "Security review assistant", "Test generation assistant"],
    creatorUtilityModules: ["Developer portal", "Documentation pack", "API console", "Analytics dashboard"],
    complianceNotes: ["Code must be reviewed and tested.", "No guarantee of bug-free or secure software."],
  },

  ai_development_app_building: {
    nicheId: "ai_development_app_building",
    packageName: "AI Development & App Building Codebase",
    maturity: "scaffold_ready",
    scaffoldPath: "app/prime-ai/ai-development-app-building",
    runtimeUrl: "/prime-ai/ai-development-app-building",
    productSurface: "No-code AI app builder and developer platform",
    frontendSurfaces: [
      "AI builder dashboard",
      "Prompt workspace",
      "App template gallery",
      "Model route selector",
      "Deployment console",
      "Developer API key page",
    ],
    backendServices: [
      "AI model router service",
      "Usage credit service",
      "App template service",
      "Deployment registry service",
      "API key management service",
    ],
    databaseModels: [
      "ai_builder_projects",
      "ai_builder_templates",
      "ai_model_routes",
      "ai_usage_credits",
      "ai_deployments",
      "developer_api_keys",
    ],
    runtimeWorkers: [
      "Prompt execution worker",
      "Model routing worker",
      "Deployment preparation worker",
      "Usage metering worker",
    ],
    rioMindNexusIntegrations: [
      "Prompt-to-app assistant",
      "Architecture generator",
      "Model selection advisor",
      "Deployment checklist assistant",
    ],
    creatorUtilityModules: [
      "Developer portal",
      "API documentation",
      "App template gallery",
      "Usage dashboard",
    ],
    complianceNotes: [
      "Generated apps require human review before production.",
      "API limits and model provider terms must be clear.",
    ],
  },

  ai_agent_marketplace: {
    nicheId: "ai_agent_marketplace",
    packageName: "AI Agent Marketplace Codebase",
    maturity: "scaffold_ready",
    scaffoldPath: "app/prime-ai/ai-agent-marketplace",
    runtimeUrl: "/prime-ai/ai-agent-marketplace",
    productSurface: "Agent catalog, install/rent workflow, execution, and publisher revenue",
    frontendSurfaces: [
      "Agent marketplace",
      "Agent detail page",
      "Install/rent flow",
      "Publisher console",
      "Agent execution logs",
      "Revenue dashboard",
    ],
    backendServices: [
      "Agent registry service",
      "Agent install service",
      "Agent execution router",
      "Publisher payout service",
      "Agent review service",
    ],
    databaseModels: [
      "ai_agents",
      "ai_agent_publishers",
      "ai_agent_installs",
      "ai_agent_runs",
      "ai_agent_reviews",
      "ai_agent_revenue",
    ],
    runtimeWorkers: [
      "Agent execution worker",
      "Agent safety summary worker",
      "Publisher revenue worker",
      "Agent telemetry worker",
    ],
    rioMindNexusIntegrations: [
      "Agent recommendation engine",
      "Agent capability reviewer",
      "Workflow execution assistant",
      "Publisher onboarding assistant",
    ],
    creatorUtilityModules: [
      "Agent catalog",
      "Marketplace module",
      "Developer portal",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "Agent capability limitations must be visible.",
      "Autonomous actions require user approval for sensitive workflows.",
    ],
  },

  student_ai_platform: {
    nicheId: "student_ai_platform",
    packageName: "Student AI Platform Codebase",
    maturity: "scaffold_ready",
    scaffoldPath: "app/prime-ai/student-ai-platform",
    runtimeUrl: "/prime-ai/student-ai-platform",
    productSurface: "AI tutor, study notes, flashcards, exam prep, and certification",
    frontendSurfaces: [
      "Student dashboard",
      "AI tutor workspace",
      "Study notes generator",
      "Flashcard workspace",
      "Exam prep page",
      "Certification page",
    ],
    backendServices: [
      "Tutor thread service",
      "Study material generator",
      "Flashcard service",
      "Progress tracker",
      "Certification proof service",
    ],
    databaseModels: [
      "learning_courses",
      "study_sessions",
      "tutor_threads",
      "flashcards",
      "student_progress",
      "learning_certifications",
    ],
    runtimeWorkers: [
      "Study note generation worker",
      "Exam prep worker",
      "Certification summary worker",
    ],
    rioMindNexusIntegrations: [
      "AI tutor",
      "Study plan generator",
      "Exam prep assistant",
      "Flashcard assistant",
    ],
    creatorUtilityModules: [
      "Education portal",
      "AI tutor module",
      "Certification proof",
      "Student analytics",
    ],
    complianceNotes: [
      "No exam cheating or impersonation support.",
      "Educational output requires learner/instructor review.",
    ],
  },

  science_virtual_lab: {
    nicheId: "science_virtual_lab",
    packageName: "Science & Virtual Lab Codebase",
    maturity: "scaffold_ready",
    scaffoldPath: "app/prime-ai/science-virtual-lab",
    runtimeUrl: "/prime-ai/science-virtual-lab",
    productSurface: "STEM labs, simulations, datasets, reports, and scientific models",
    frontendSurfaces: [
      "Virtual lab dashboard",
      "Experiment selector",
      "Simulation canvas",
      "Dataset viewer",
      "Lab report page",
      "Science model library",
    ],
    backendServices: [
      "Experiment registry service",
      "Simulation orchestration service",
      "Dataset registry service",
      "Lab report service",
      "Scientific model service",
    ],
    databaseModels: [
      "virtual_labs",
      "lab_experiments",
      "lab_simulations",
      "lab_datasets",
      "lab_reports",
      "scientific_models",
    ],
    runtimeWorkers: [
      "Simulation worker",
      "Scientific calculation worker",
      "Report generation worker",
    ],
    rioMindNexusIntegrations: [
      "Experiment explainer",
      "Simulation setup assistant",
      "Lab report assistant",
      "Scientific model interpreter",
    ],
    creatorUtilityModules: [
      "Virtual lab",
      "Research portal",
      "Education portal",
      "Certification proof",
    ],
    complianceNotes: [
      "Simulations are educational approximations unless validated.",
      "Dataset sources must be disclosed.",
    ],
  },

  research_economy: {
    nicheId: "research_economy",
    packageName: "Research Economy Codebase",
    maturity: "scaffold_ready",
    productSurface: "Research proposals, grants, peer review, publications, and citation proof",
    frontendSurfaces: [
      "Research portal",
      "Proposal builder",
      "Grant board",
      "Peer review dashboard",
      "Publication profile",
      "Researcher profile",
    ],
    backendServices: [
      "Proposal workflow service",
      "Grant registry service",
      "Peer review service",
      "Citation metadata service",
      "Research reputation service",
    ],
    databaseModels: [
      "research_profiles",
      "research_proposals",
      "research_grants",
      "research_reviews",
      "research_citations",
      "research_publications",
    ],
    runtimeWorkers: [
      "Literature review worker",
      "Citation extraction worker",
      "Peer review summary worker",
    ],
    rioMindNexusIntegrations: [
      "Proposal drafting assistant",
      "Literature review assistant",
      "Citation assistant",
      "Grant evaluation assistant",
    ],
    creatorUtilityModules: [
      "Research portal",
      "Documentation pack",
      "Dataset marketplace",
      "Verification layer",
    ],
    complianceNotes: [
      "Research claims require source support.",
      "Grant and peer review rules must be transparent.",
    ],
  },

  data_marketplace: {
    nicheId: "data_marketplace",
    packageName: "Data Marketplace Codebase",
    maturity: "scaffold_ready",
    productSurface: "Dataset catalog, upload, licensing, provenance, quality proof, and enterprise access",
    frontendSurfaces: [
      "Dataset marketplace",
      "Dataset detail page",
      "Contributor upload portal",
      "License selection page",
      "Buyer dashboard",
      "Quality review page",
    ],
    backendServices: [
      "Dataset registry service",
      "License management service",
      "Access control service",
      "Provenance service",
      "Quality review service",
    ],
    databaseModels: [
      "datasets",
      "dataset_licenses",
      "dataset_contributors",
      "dataset_purchases",
      "dataset_provenance",
      "dataset_quality_reviews",
    ],
    runtimeWorkers: [
      "Dataset ingestion worker",
      "Quality review worker",
      "License validation worker",
    ],
    rioMindNexusIntegrations: [
      "Dataset summary assistant",
      "License explanation assistant",
      "Data quality assistant",
      "Buyer recommendation assistant",
    ],
    creatorUtilityModules: [
      "Dataset marketplace",
      "Marketplace module",
      "Verification layer",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "Dataset ownership and privacy must be clear.",
      "Sensitive data requires compliance review.",
    ],
  },

  ai_trading_intelligence: {
    nicheId: "ai_trading_intelligence",
    packageName: "AI Trading Intelligence Codebase",
    maturity: "scaffold_ready",
    productSurface: "Trading signals, strategy marketplace, portfolio tools, backtesting, and risk scoring",
    frontendSurfaces: [
      "Trading AI dashboard",
      "Signals page",
      "Strategy marketplace",
      "Backtesting page",
      "Portfolio view",
      "Risk dashboard",
    ],
    backendServices: [
      "Market data adapter",
      "Signal service",
      "Strategy registry service",
      "Backtesting service",
      "Risk scoring service",
    ],
    databaseModels: [
      "trading_strategies",
      "trading_signals",
      "strategy_backtests",
      "trading_portfolios",
      "risk_scores",
      "trading_subscriptions",
    ],
    runtimeWorkers: [
      "Market analysis worker",
      "Backtesting worker",
      "Risk scoring worker",
      "Signal generation worker",
    ],
    rioMindNexusIntegrations: [
      "Market analysis assistant",
      "Strategy explainer",
      "Portfolio review assistant",
      "Risk summary assistant",
    ],
    creatorUtilityModules: [
      "Trading dashboard",
      "Telegram alert utility",
      "Analytics dashboard",
      "Risk disclosure pack",
    ],
    complianceNotes: [
      "Not financial advice.",
      "No profit guarantee.",
      "Trading involves risk.",
    ],
  },

  ai_creator_studio: {
    nicheId: "ai_creator_studio",
    packageName: "AI Creator Studio Codebase",
    maturity: "scaffold_ready",
    productSurface: "Content generation, campaigns, templates, exports, and creator subscriptions",
    frontendSurfaces: [
      "Creator AI dashboard",
      "Content workspace",
      "Template gallery",
      "Campaign calendar",
      "Export center",
      "Creator subscriptions",
    ],
    backendServices: [
      "Content generation service",
      "Template registry service",
      "Campaign service",
      "Export service",
      "Subscription service",
    ],
    databaseModels: [
      "creator_projects",
      "creator_templates",
      "content_jobs",
      "creator_campaigns",
      "creator_exports",
      "creator_subscriptions",
    ],
    runtimeWorkers: [
      "Content generation worker",
      "Campaign planner worker",
      "Export formatter worker",
    ],
    rioMindNexusIntegrations: [
      "Script generator",
      "Campaign planner",
      "Brand voice assistant",
      "Content workflow assistant",
    ],
    creatorUtilityModules: [
      "Project website",
      "Social launch kit",
      "Template marketplace",
      "Creator analytics",
    ],
    complianceNotes: [
      "Creators are responsible for copyright.",
      "AI-generated content requires review before publishing.",
    ],
  },

  ai_social_platform: {
    nicheId: "ai_social_platform",
    packageName: "AI Social Platform Codebase",
    maturity: "scaffold_ready",
    productSurface: "Social feed, creator rewards, community governance, moderation, and engagement intelligence",
    frontendSurfaces: [
      "Social feed",
      "Creator profiles",
      "Community spaces",
      "Engagement dashboard",
      "Reward page",
      "Moderation dashboard",
    ],
    backendServices: [
      "Post registry service",
      "Engagement tracking service",
      "Reward calculation service",
      "Community governance service",
      "Moderation service",
    ],
    databaseModels: [
      "social_posts",
      "social_creators",
      "social_engagements",
      "social_rewards",
      "social_communities",
      "moderation_events",
    ],
    runtimeWorkers: [
      "Engagement scoring worker",
      "Reward risk worker",
      "AI moderation worker",
    ],
    rioMindNexusIntegrations: [
      "Content moderation assistant",
      "Creator growth assistant",
      "Engagement summary assistant",
      "Community governance assistant",
    ],
    creatorUtilityModules: [
      "Social launch kit",
      "Telegram utility",
      "Token-gated access",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "Anti-spam and reward farming controls are required.",
      "Human moderation remains important.",
    ],
  },

  enterprise_ai_automation: {
    nicheId: "enterprise_ai_automation",
    packageName: "Enterprise AI Automation Codebase",
    maturity: "scaffold_ready",
    productSurface: "B2B workflow automation, support agents, documents, audit logs, and service plans",
    frontendSurfaces: [
      "Enterprise AI console",
      "Workflow builder",
      "Automation status board",
      "Document intelligence page",
      "Reports dashboard",
      "Organization settings",
    ],
    backendServices: [
      "Organization service",
      "Workflow engine",
      "Automation service",
      "Audit log service",
      "Billing/service plan service",
    ],
    databaseModels: [
      "enterprise_organizations",
      "enterprise_workflows",
      "enterprise_automations",
      "enterprise_audit_logs",
      "enterprise_service_plans",
      "enterprise_users",
    ],
    runtimeWorkers: [
      "Workflow execution worker",
      "Document summary worker",
      "Audit report worker",
    ],
    rioMindNexusIntegrations: [
      "Workflow builder assistant",
      "Customer support agent",
      "Document summary assistant",
      "Automation recommendation engine",
    ],
    creatorUtilityModules: [
      "App experience template",
      "Documentation pack",
      "Analytics dashboard",
      "Verification layer",
    ],
    complianceNotes: [
      "Business data requires privacy controls.",
      "Sensitive automations require approval.",
    ],
  },

  healthcare_medical_ai: {
    nicheId: "healthcare_medical_ai",
    packageName: "Healthcare & Medical AI Codebase",
    maturity: "scaffold_ready",
    productSurface: "Healthcare research, provider workflows, consent, privacy, audit logs, and compliance review",
    frontendSurfaces: [
      "Healthcare AI portal",
      "Research workspace",
      "Provider dashboard",
      "Health data access page",
      "Compliance review page",
      "Audit log page",
    ],
    backendServices: [
      "Provider registry service",
      "Research case service",
      "Consent record service",
      "Health data access service",
      "Compliance review service",
    ],
    databaseModels: [
      "health_providers",
      "health_research_cases",
      "health_consent_records",
      "health_data_access",
      "health_audit_logs",
      "health_compliance_reviews",
    ],
    runtimeWorkers: [
      "Medical literature summary worker",
      "Compliance checklist worker",
      "Audit report worker",
    ],
    rioMindNexusIntegrations: [
      "Medical literature assistant",
      "Provider workflow assistant",
      "Compliance checklist assistant",
      "Patient-safe explanation assistant",
    ],
    creatorUtilityModules: [
      "Research portal",
      "Documentation pack",
      "Verification layer",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "Not a doctor or emergency service.",
      "No diagnosis guarantee.",
      "Health data requires compliance review.",
    ],
  },

  ai_freelance_work_marketplace: {
    nicheId: "ai_freelance_work_marketplace",
    packageName: "AI Freelance & Work Marketplace Codebase",
    maturity: "scaffold_ready",
    productSurface: "Jobs, offers, service listings, escrow, disputes, reviews, and freelancer profiles",
    frontendSurfaces: [
      "Work AI marketplace",
      "Job board",
      "Freelancer profiles",
      "Service listing page",
      "Escrow status page",
      "Dispute center",
    ],
    backendServices: [
      "Job registry service",
      "Offer service",
      "Escrow service",
      "Dispute workflow service",
      "Reputation service",
    ],
    databaseModels: [
      "work_jobs",
      "work_offers",
      "work_escrows",
      "work_disputes",
      "work_reviews",
      "freelancer_profiles",
    ],
    runtimeWorkers: [
      "Freelancer matching worker",
      "Escrow summary worker",
      "Reputation scoring worker",
    ],
    rioMindNexusIntegrations: [
      "Job description assistant",
      "Freelancer matching assistant",
      "Dispute review assistant",
      "Reputation summary assistant",
    ],
    creatorUtilityModules: [
      "Marketplace module",
      "Verification layer",
      "Telegram utility",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "Escrow terms must be clear.",
      "Dispute rules should be transparent.",
    ],
  },

  developer_ai_ecosystem: {
    nicheId: "developer_ai_ecosystem",
    packageName: "Developer AI Ecosystem Codebase",
    maturity: "scaffold_ready",
    productSurface: "Developer portal, APIs, SDKs, bounties, grants, deployment console, and usage metering",
    frontendSurfaces: [
      "Developer AI portal",
      "API dashboard",
      "SDK documentation",
      "Bug bounty board",
      "Grant board",
      "Deployment console",
    ],
    backendServices: [
      "Developer registry service",
      "API key service",
      "SDK download service",
      "Bounty service",
      "Grant workflow service",
      "Deployment metadata service",
    ],
    databaseModels: [
      "developer_profiles",
      "developer_api_keys",
      "sdk_downloads",
      "developer_bounties",
      "developer_grants",
      "developer_deployments",
    ],
    runtimeWorkers: [
      "API usage worker",
      "Bounty review worker",
      "Deployment guide worker",
    ],
    rioMindNexusIntegrations: [
      "SDK assistant",
      "API integration assistant",
      "Code review assistant",
      "Bug bounty assistant",
      "Deployment guide assistant",
    ],
    creatorUtilityModules: [
      "Developer portal",
      "API documentation",
      "Documentation pack",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "API terms and limits must be clear.",
      "SDK license should be disclosed.",
    ],
  },

  ai_business_launch_hub: {
    nicheId: "ai_business_launch_hub",
    packageName: "AI Business Launch Hub Codebase",
    maturity: "scaffold_ready",
    productSurface: "Business app generator, CRM, e-commerce, school portal, support agents, and workflow tools",
    frontendSurfaces: [
      "Business AI launcher",
      "Template selector",
      "Generated app preview",
      "CRM workspace",
      "Support agent page",
      "Billing/subscription page",
    ],
    backendServices: [
      "Business template service",
      "Generated app service",
      "Deployment service",
      "Support agent service",
      "Subscription service",
    ],
    databaseModels: [
      "business_templates",
      "business_generated_apps",
      "business_deployments",
      "business_subscriptions",
      "business_support_agents",
    ],
    runtimeWorkers: [
      "App generation worker",
      "Support agent setup worker",
      "Deployment metadata worker",
    ],
    rioMindNexusIntegrations: [
      "Business app generator",
      "CRM setup assistant",
      "Support agent builder",
      "Sales workflow assistant",
    ],
    creatorUtilityModules: [
      "App experience template",
      "Project website",
      "Documentation pack",
      "Analytics dashboard",
    ],
    complianceNotes: [
      "Generated apps require review before business use.",
      "Customer data handling must be clear.",
    ],
  },

  ai_education_research_ecosystem: {
    nicheId: "ai_education_research_ecosystem",
    packageName: "AI Education & Research Ecosystem Codebase",
    maturity: "scaffold_ready",
    productSurface: "Full AI ecosystem for learning, research, agents, datasets, credentials, grants, and developer apps",
    frontendSurfaces: [
      "AI ecosystem dashboard",
      "Learning module",
      "Research module",
      "Agent marketplace",
      "Dataset marketplace",
      "Credentials page",
      "Developer app marketplace",
    ],
    backendServices: [
      "Learning service",
      "Research service",
      "Agent registry service",
      "Dataset service",
      "Credential proof service",
      "Grant service",
      "Developer app service",
    ],
    databaseModels: [
      "ecosystem_learning",
      "ecosystem_research",
      "ecosystem_agents",
      "ecosystem_datasets",
      "ecosystem_credentials",
      "ecosystem_grants",
      "ecosystem_developer_apps",
    ],
    runtimeWorkers: [
      "Learning assistant worker",
      "Research assistant worker",
      "Agent execution worker",
      "Dataset summary worker",
      "Credential proof worker",
    ],
    rioMindNexusIntegrations: [
      "Unified ecosystem assistant",
      "Student tutor",
      "Research assistant",
      "Agent marketplace assistant",
      "Dataset assistant",
      "Credential proof assistant",
      "Developer app assistant",
    ],
    creatorUtilityModules: [
      "Education portal",
      "Research portal",
      "Agent catalog",
      "Dataset marketplace",
      "Developer portal",
      "Verification layer",
    ],
    complianceNotes: [
      "Academic integrity rules apply.",
      "Research and credential claims require proof.",
      "AI outputs require review.",
    ],
  },
};

export function getPrimeAiCodebasePackage(nicheId?: string | null): PrimeAiCodebasePackage {
  const id = String(nicheId || "").trim();
  return PACKAGES[id] || { ...GENERIC_AI_CODEBASE, nicheId: id || GENERIC_AI_CODEBASE.nicheId };
}
