import crypto from "crypto";
import fs from "fs/promises";
import path from "path";

export type CreatePptxArtifactInput = {
  ownerKey: string;
  title?: string;
  content?: unknown;
  sections?: unknown;
  columns?: unknown;
  rows?: unknown;
};

export type CreatePptxArtifactResult = {
  id: string;
  type: "pptx";
  name: string;
  title: string;
  path: string;
  downloadUrl: string;
  slideCount: number;
  tableCount: number;
  sectionCount: number;
};

type PptxRow = Record<string, unknown>;

function safeFileTitle(value: unknown) {
  const raw = typeof value === "string" && value.trim() ? value.trim() : "nexus presentation";
  return raw
    .replace(/[\\/:*?"<>|]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80) || "nexus presentation";
}

function normalizeOwnerKey(value: string) {
  return value.replace(/[^a-zA-Z0-9_.-]/g, "_").slice(0, 80) || "local_dev";
}

function text(value: unknown) {
  if (value === null || value === undefined) return "";
  return String(value).trim();
}

function normalizeRows(rows: unknown) {
  if (!Array.isArray(rows)) return [];

  return rows
    .map((row) => {
      if (row && typeof row === "object" && !Array.isArray(row)) {
        return { ...(row as PptxRow) };
      }

      if (Array.isArray(row)) {
        const output: PptxRow = {};
        row.forEach((value, index) => {
          output[`Column ${index + 1}`] = value ?? "";
        });
        return output;
      }

      return { Item: row ?? "" };
    })
    .filter((row) => Object.keys(row).length > 0);
}

function normalizeColumns(columns: unknown, rows: PptxRow[]) {
  if (Array.isArray(columns)) {
    const cleaned = columns.map((column) => text(column)).filter(Boolean);
    if (cleaned.length > 0) return Array.from(new Set(cleaned));
  }

  const discovered = new Set<string>();
  for (const row of rows) {
    for (const key of Object.keys(row)) discovered.add(key);
  }

  return Array.from(discovered);
}

function normalizeSections(sections: unknown, content: unknown) {
  if (Array.isArray(sections)) {
    const normalized = sections
      .map((section) => {
        if (typeof section === "string") {
          return { heading: "", body: section.trim() };
        }

        if (section && typeof section === "object" && !Array.isArray(section)) {
          const record = section as Record<string, unknown>;
          return {
            heading: text(record.heading ?? record.title ?? ""),
            body: text(record.body ?? record.content ?? record.text ?? ""),
          };
        }

        return { heading: "", body: "" };
      })
      .filter((section) => section.heading || section.body);

    if (normalized.length > 0) return normalized;
  }

  const body = text(content);
  if (!body) {
    return [{ heading: "Overview", body: "This presentation was generated by RioMind Nexus." }];
  }

  return splitMarkdownLikeContent(body);
}

function splitMarkdownLikeContent(content: string) {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  const sections: Array<{ heading: string; body: string }> = [];
  let heading = "Overview";
  let body: string[] = [];

  function flush() {
    const joined = body.join("\n").trim();
    if (heading || joined) sections.push({ heading, body: joined });
    body = [];
  }

  for (const line of lines) {
    const trimmed = line.trim();

    if (/^#{1,3}\s+/.test(trimmed)) {
      flush();
      heading = trimmed.replace(/^#{1,3}\s+/, "").trim() || "Section";
      continue;
    }

    body.push(line);
  }

  flush();
  return sections.filter((section) => section.heading || section.body);
}

function bulletsFromBody(body: string) {
  const lines = body
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) return ["Generated by RioMind Nexus."];

  const bullets = lines.map((line) => line.replace(/^[-*]\s+/, "").trim()).filter(Boolean);
  return bullets.slice(0, 8);
}

function shortValue(value: unknown, max = 28) {
  const raw = text(value);
  if (raw.length <= max) return raw;
  return `${raw.slice(0, max - 1)}…`;
}

function addFooter(slide: any) {
  slide.addText("RioMind Nexus", {
    x: 0.55,
    y: 7.05,
    w: 2.4,
    h: 0.22,
    fontFace: "Aptos",
    fontSize: 8,
    color: "94A3B8",
  });
}

function addTitleSlide(pptx: any, title: string) {
  const slide = pptx.addSlide();
  slide.background = { color: "0F172A" };

  slide.addText("RioMind Nexus", {
    x: 0.65,
    y: 0.45,
    w: 3.2,
    h: 0.35,
    fontFace: "Aptos",
    fontSize: 14,
    bold: true,
    color: "38BDF8",
  });

  slide.addText(title, {
    x: 0.65,
    y: 2.45,
    w: 12.0,
    h: 1.2,
    fontFace: "Aptos",
    fontSize: 34,
    bold: true,
    color: "FFFFFF",
    fit: "shrink",
  });

  slide.addText("Generated presentation artifact", {
    x: 0.68,
    y: 3.75,
    w: 8.4,
    h: 0.42,
    fontFace: "Aptos",
    fontSize: 15,
    color: "CBD5E1",
  });

  slide.addShape(pptx.ShapeType.rect, {
    x: 0.65,
    y: 4.55,
    w: 3.0,
    h: 0.05,
    fill: { color: "38BDF8" },
    line: { color: "38BDF8" },
  });

  return slide;
}

function addSectionSlide(pptx: any, heading: string, body: string) {
  const slide = pptx.addSlide();
  slide.background = { color: "F8FAFC" };

  slide.addText(heading || "Overview", {
    x: 0.55,
    y: 0.45,
    w: 12.0,
    h: 0.5,
    fontFace: "Aptos",
    fontSize: 24,
    bold: true,
    color: "0F172A",
    fit: "shrink",
  });

  const bullets = bulletsFromBody(body);

  slide.addText(
    bullets.map((item) => ({ text: item, options: { bullet: { indent: 16 }, hanging: 4 } })),
    {
      x: 0.85,
      y: 1.45,
      w: 11.5,
      h: 4.9,
      fontFace: "Aptos",
      fontSize: 16,
      color: "1F2937",
      breakLine: false,
      fit: "shrink",
      valign: "top",
    }
  );

  addFooter(slide);
  return slide;
}

function addTableSlide(pptx: any, title: string, columns: string[], rows: PptxRow[]) {
  const slide = pptx.addSlide();
  slide.background = { color: "F8FAFC" };

  slide.addText(title || "Table", {
    x: 0.55,
    y: 0.45,
    w: 12.0,
    h: 0.5,
    fontFace: "Aptos",
    fontSize: 24,
    bold: true,
    color: "0F172A",
    fit: "shrink",
  });

  const usableColumns = columns.slice(0, 6);
  const usableRows = rows.slice(0, 10);

  const tableData = [
    usableColumns.map((column) => ({
      text: shortValue(column, 20),
      options: {
        bold: true,
        color: "FFFFFF",
        fill: { color: "111827" },
        fontFace: "Aptos",
        fontSize: 9,
        margin: 0.04,
      },
    })),
    ...usableRows.map((row, rowIndex) =>
      usableColumns.map((column) => ({
        text: shortValue((row as Record<string, unknown>)[column], 24),
        options: {
          color: "111827",
          fill: { color: rowIndex % 2 === 0 ? "FFFFFF" : "E2E8F0" },
          fontFace: "Aptos",
          fontSize: 8,
          margin: 0.04,
        },
      }))
    ),
  ];

  slide.addTable(tableData, {
    x: 0.55,
    y: 1.25,
    w: 12.2,
    h: 5.3,
    border: { type: "solid", color: "CBD5E1", pt: 0.5 },
    valign: "mid",
    fit: "shrink",
  });

  addFooter(slide);
  return slide;
}

export async function createPptxArtifact(
  input: CreatePptxArtifactInput
): Promise<CreatePptxArtifactResult> {
  const pptxModule = await import("pptxgenjs");
  const PptxGenJS = ((pptxModule as unknown as { default?: any }).default ?? pptxModule) as any;

  const title = safeFileTitle(input.title);
  const id = crypto.randomUUID();
  const shortId = id.slice(0, 8);
  const name = `${title}-${shortId}.pptx`;

  const sections = normalizeSections(input.sections, input.content);
  const rows = normalizeRows(input.rows);
  const columns = normalizeColumns(input.columns, rows);

  const pptx = new PptxGenJS();
  pptx.author = "RioMind Nexus";
  pptx.company = "RioMind Nexus";
  pptx.subject = "Generated by RioMind Nexus";
  pptx.title = title;
  pptx.lang = "en-US";
  pptx.layout = "LAYOUT_WIDE";
  pptx.theme = {
    headFontFace: "Aptos Display",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };

  let slideCount = 0;
  let tableCount = 0;

  addTitleSlide(pptx, title);
  slideCount += 1;

  for (const section of sections.slice(0, 8)) {
    addSectionSlide(pptx, section.heading, section.body);
    slideCount += 1;
  }

  if (rows.length > 0 && columns.length > 0) {
    addTableSlide(pptx, "Data Table", columns, rows);
    slideCount += 1;
    tableCount += 1;
  }

  const ownerKey = normalizeOwnerKey(input.ownerKey);
  const uploadRoot = process.env.RIOMIND_UPLOAD_DIR || "/app/.riomind_uploads";
  const artifactDir = path.join(uploadRoot, ownerKey, "artifacts");
  await fs.mkdir(artifactDir, { recursive: true });

  const filePath = path.join(artifactDir, name);
  await pptx.writeFile({ fileName: filePath });

  return {
    id,
    type: "pptx",
    name,
    title,
    path: filePath,
    downloadUrl: `/api/riomind/artifacts/download?name=${encodeURIComponent(name)}`,
    slideCount,
    tableCount,
    sectionCount: sections.length,
  };
}
