export const PUMP_GRADUATION_TARGET_RUSD = 65_000;
export const PUMP_GRADUATION_SEED_RUSD = 15_000;

export const PUMP_GRADUATION_REWARD_RESERVE_RUSD = 5_000;

export const PUMP_CREATOR_REWARD_TOTAL_PERCENT = 10;
export const PUMP_CREATOR_REWARD_STAGE_PERCENT = 5;

// Market-cap thresholds are RIO-settled and measured through RIO/RUSD valuation.
// They do not mean literal RUSD custody or literal RUSD payment.
export const PUMP_REWARD_STAGE_ONE_MARKET_CAP_RUSD_EQUIVALENT = 250_000;
export const PUMP_REWARD_STAGE_ONE_MARKET_CAP_RUSD =
  PUMP_REWARD_STAGE_ONE_MARKET_CAP_RUSD_EQUIVALENT;
export const PUMP_REWARD_STAGE_ONE_SUSTAIN_DAYS = 3;
export const PUMP_REWARD_STAGE_ONE_ORGANIC_BUYERS_MIN = 100;
export const PUMP_REWARD_STAGE_ONE_ORGANIC_BUYERS_TARGET = 150;

export const PUMP_REWARD_STAGE_TWO_MARKET_CAP_RUSD_EQUIVALENT = 500_000;
export const PUMP_REWARD_STAGE_TWO_MARKET_CAP_RUSD =
  PUMP_REWARD_STAGE_TWO_MARKET_CAP_RUSD_EQUIVALENT;
export const PUMP_REWARD_STAGE_TWO_SUSTAIN_DAYS = 4;
export const PUMP_REWARD_STAGE_TWO_ORGANIC_BUYERS_MIN = 250;
export const PUMP_REWARD_STAGE_TWO_ORGANIC_BUYERS_TARGET = 400;

export const PUMP_REWARD_STAGE_THREE_MARKET_CAP_RUSD_EQUIVALENT = 1_000_000;
export const PUMP_REWARD_STAGE_THREE_MARKET_CAP_RUSD =
  PUMP_REWARD_STAGE_THREE_MARKET_CAP_RUSD_EQUIVALENT;
export const PUMP_REWARD_STAGE_THREE_REWARD_PERCENT = 2.5;
export const PUMP_REWARD_STAGE_THREE_REQUIRED_SWAPS = 1_000;
export const PUMP_REWARD_STAGE_THREE_ORGANIC_BUYERS_MIN = 600;
export const PUMP_REWARD_STAGE_THREE_ORGANIC_BUYERS_TARGET = 1_000;

export const PUMP_REWARD_STABLE_PAYOUT_PERCENT = 80;
export const PUMP_REWARD_RIO_PAYOUT_PERCENT = 20;

export const PUMP_REWARD_REQUIRES_LP_SEED_PROOF = true;
export const PUMP_REWARD_REQUIRES_ANTI_ABUSE_CLEARANCE = true;
export const PUMP_REWARD_ALLOW_INSTANT_POST_GRADUATION_PAYOUT = false;

// Backward-compatible default for legacy consumers.
// Stage-specific sustain windows should prefer the explicit constants above.
export const PUMP_REWARD_SUSTAIN_DAYS = PUMP_REWARD_STAGE_TWO_SUSTAIN_DAYS;

// Dev/reference conversion. Later this should come from RIO/RUSD TWAP.
export const PUMP_RIO_REFERENCE_PRICE_RUSD = 0.1;

export const PUMP_GRADUATION_TARGET_RIO =
  PUMP_GRADUATION_TARGET_RUSD / PUMP_RIO_REFERENCE_PRICE_RUSD;

export const PUMP_GRADUATION_TARGET_URIO =
  Math.round(PUMP_GRADUATION_TARGET_RIO * 1_000_000);

export const PUMP_GRADUATION_REMAINING_AFTER_SEED_RUSD =
  PUMP_GRADUATION_TARGET_RUSD - PUMP_GRADUATION_SEED_RUSD;

export const PUMP_CREATOR_REWARD_TOTAL_RUSD =
  PUMP_GRADUATION_REMAINING_AFTER_SEED_RUSD *
  (PUMP_CREATOR_REWARD_TOTAL_PERCENT / 100);

export const PUMP_CREATOR_REWARD_STAGE_RUSD =
  PUMP_GRADUATION_REMAINING_AFTER_SEED_RUSD *
  (PUMP_CREATOR_REWARD_STAGE_PERCENT / 100);
