export const RIOMIND_PROVIDER_REGISTRY = [
  {
    id: "openai",
    name: "OpenAI",
    category: "reasoning",
    strengths: ["reasoning", "planning", "general", "agents"],
    costTier: "premium",
    status: "planned",
    enabled: false,
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    category: "analysis",
    strengths: ["analysis", "writing", "long_context"],
    costTier: "premium",
    status: "planned",
    enabled: false,
  },
  {
    id: "gemini",
    name: "Google Gemini",
    category: "research",
    strengths: ["research", "multimodal", "web"],
    costTier: "premium",
    status: "planned",
    enabled: false,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "coding",
    strengths: ["coding", "reasoning"],
    costTier: "economy",
    status: "planned",
    enabled: false,
  },
  {
    id: "grok",
    name: "Grok",
    category: "realtime",
    strengths: ["realtime", "news", "social"],
    costTier: "premium",
    status: "planned",
    enabled: false,
  },
  {
    id: "mistral",
    name: "Mistral",
    category: "open",
    strengths: ["reasoning", "efficiency"],
    costTier: "economy",
    status: "planned",
    enabled: false,
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "enterprise",
    strengths: ["enterprise", "retrieval", "rag"],
    costTier: "premium",
    status: "planned",
    enabled: false,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "research",
    strengths: ["research", "citations", "web"],
    costTier: "premium",
    status: "planned",
    enabled: false,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregation",
    strengths: ["routing", "multi_model"],
    costTier: "variable",
    status: "planned",
    enabled: false,
  },
  {
    id: "local_models",
    name: "Local Models",
    category: "private",
    strengths: ["privacy", "offline", "custom"],
    costTier: "low",
    status: "planned",
    enabled: false,
  }
];
