import type {
  NexusWorkspaceModuleManifest,
} from "./workspace-types";

const allWorkspaceTypes = [
  "meeting",
  "project",
  "research",
  "classroom",
  "development",
  "sales",
] as const;

export const NEXUS_WORKSPACE_MODULE_MANIFESTS = [
  {
    id: "meeting",
    name: "Meeting Stage",
    description:
      "Primary live meeting, presentation, lobby, and participant stage.",
    version: "1.0.0",
    region: "primary",
    order: 10,
    supportedWorkspaceTypes: ["meeting"],
    runtimeDependencies: [
      "meeting",
      "participants",
      "presence",
      "media",
      "realtime",
    ],
    requiredPermissions: ["view"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "toolbar",
    name: "Meeting Controls",
    description:
      "Meeting, media, collaboration, and lifecycle command controls.",
    version: "1.0.0",
    region: "header",
    order: 20,
    supportedWorkspaceTypes: ["meeting"],
    runtimeDependencies: [
      "meeting",
      "participants",
      "media",
      "realtime",
    ],
    requiredPermissions: ["participate"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "participants",
    name: "Participants",
    description:
      "Canonical participant directory, roles, presence, and media state.",
    version: "1.0.0",
    region: "secondary",
    order: 30,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: [
      "participants",
      "presence",
      "media",
      "realtime",
    ],
    requiredPermissions: ["view"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "voice",
    name: "Voice",
    description:
      "Voice collaboration, audio routing, speaking, and recording controls.",
    version: "1.0.0",
    region: "secondary",
    order: 40,
    supportedWorkspaceTypes: [
      "meeting",
      "classroom",
      "sales",
    ],
    runtimeDependencies: [
      "participants",
      "media",
      "translation",
      "realtime",
    ],
    requiredPermissions: ["participate"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "translation",
    name: "Translation",
    description:
      "Participant-owned language, captions, and live translation controls.",
    version: "1.0.0",
    region: "secondary",
    order: 50,
    supportedWorkspaceTypes: [
      "meeting",
      "research",
      "classroom",
      "sales",
    ],
    runtimeDependencies: [
      "participants",
      "translation",
      "realtime",
    ],
    requiredPermissions: ["view"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "transcript",
    name: "Live Transcript",
    description:
      "Live transcript, captions, speaker turns, and searchable meeting text.",
    version: "1.0.0",
    region: "secondary",
    order: 60,
    supportedWorkspaceTypes: [
      "meeting",
      "research",
      "classroom",
      "sales",
    ],
    runtimeDependencies: [
      "meeting",
      "participants",
      "translation",
      "assistant",
      "realtime",
    ],
    requiredPermissions: ["view"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "assistant",
    name: "Meeting Assistant",
    description:
      "Meeting summaries, decisions, action items, risks, and memory.",
    version: "1.0.0",
    region: "right_rail",
    order: 70,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: [
      "meeting",
      "participants",
      "assistant",
      "realtime",
    ],
    requiredPermissions: ["view"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "chat",
    name: "Chat",
    description:
      "Shared workspace and meeting conversation.",
    version: "1.0.0",
    region: "secondary",
    order: 80,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: [
      "meeting",
      "participants",
      "workspace",
      "realtime",
    ],
    requiredPermissions: ["participate"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "files",
    name: "Files",
    description:
      "Shared workspace files and meeting attachments.",
    version: "1.0.0",
    region: "secondary",
    order: 90,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: ["workspace", "realtime"],
    requiredPermissions: ["view"],
    enabledByDefault: true,
    singleton: true,
    experimental: false,
  },
  {
    id: "notes",
    name: "Shared Notes",
    description:
      "Collaborative meeting and workspace notes.",
    version: "1.0.0",
    region: "secondary",
    order: 100,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: [
      "meeting",
      "participants",
      "workspace",
      "realtime",
    ],
    requiredPermissions: ["participate"],
    enabledByDefault: false,
    singleton: true,
    experimental: false,
  },
  {
    id: "documents",
    name: "Shared Documents",
    description:
      "Collaborative structured documents and revisions.",
    version: "1.0.0",
    region: "secondary",
    order: 110,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: [
      "participants",
      "workspace",
      "realtime",
    ],
    requiredPermissions: ["participate"],
    enabledByDefault: false,
    singleton: false,
    experimental: false,
  },
  {
    id: "whiteboard",
    name: "Whiteboard",
    description:
      "Collaborative visual canvas, diagrams, notes, and brainstorming.",
    version: "1.0.0",
    region: "primary",
    order: 120,
    supportedWorkspaceTypes: [
      "meeting",
      "project",
      "research",
      "classroom",
      "development",
    ],
    runtimeDependencies: [
      "participants",
      "workspace",
      "realtime",
    ],
    requiredPermissions: ["participate"],
    enabledByDefault: false,
    singleton: true,
    experimental: true,
  },
  {
    id: "analytics",
    name: "Analytics",
    description:
      "Workspace activity, meeting engagement, and collaboration intelligence.",
    version: "1.0.0",
    region: "secondary",
    order: 130,
    supportedWorkspaceTypes: allWorkspaceTypes,
    runtimeDependencies: [
      "meeting",
      "participants",
      "workspace",
    ],
    requiredPermissions: ["view"],
    enabledByDefault: false,
    singleton: true,
    experimental: false,
  },
] as const satisfies readonly NexusWorkspaceModuleManifest[];
