export type PrimeAiNexusRegistryItem = {
  id: string;
  title: string;
  slug: string;
  runtimePath: string;
  apiPath: string;
  status: "nexus_ready_not_connected";
  category: string;
};

export const PRIME_AI_NEXUS_REGISTRY: PrimeAiNexusRegistryItem[] = [
  {
    id: "student_ai_platform",
    title: "Student AI Platform",
    slug: "student-ai-platform",
    runtimePath: "/prime-ai/student-ai-platform",
    apiPath: "/api/prime-ai/student-ai-platform/deep-learning",
    status: "nexus_ready_not_connected",
    category: "Education",
  },
  {
    id: "science_virtual_lab",
    title: "Science & Virtual Lab Platform",
    slug: "science-virtual-lab",
    runtimePath: "/prime-ai/science-virtual-lab",
    apiPath: "/api/prime-ai/science-virtual-lab/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "STEM / Research",
  },
  {
    id: "ai_development_app_building",
    title: "AI Development & App Building",
    slug: "ai-development-app-building",
    runtimePath: "/prime-ai/ai-development-app-building",
    apiPath: "/api/prime-ai/ai-development-app-building/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "AI App Builder",
  },
  {
    id: "ai_agent_marketplace",
    title: "AI Agent Marketplace",
    slug: "ai-agent-marketplace",
    runtimePath: "/prime-ai/ai-agent-marketplace",
    apiPath: "/api/prime-ai/ai-agent-marketplace/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Agent Marketplace",
  },
  {
    id: "research_economy",
    title: "Research Economy",
    slug: "research-economy",
    runtimePath: "/prime-ai/research-economy",
    apiPath: "/api/prime-ai/research-economy/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Research",
  },
  {
    id: "data_marketplace",
    title: "Data Marketplace",
    slug: "data-marketplace",
    runtimePath: "/prime-ai/data-marketplace",
    apiPath: "/api/prime-ai/data-marketplace/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Data Marketplace",
  },
  {
    id: "ai_trading_intelligence",
    title: "AI Trading Intelligence",
    slug: "ai-trading-intelligence",
    runtimePath: "/prime-ai/ai-trading-intelligence",
    apiPath: "/api/prime-ai/ai-trading-intelligence/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Trading / Markets",
  },
  {
    id: "ai_creator_studio",
    title: "AI Creator Studio",
    slug: "ai-creator-studio",
    runtimePath: "/prime-ai/ai-creator-studio",
    apiPath: "/api/prime-ai/ai-creator-studio/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Creator Economy",
  },
  {
    id: "ai_social_platform",
    title: "AI Social Platform",
    slug: "ai-social-platform",
    runtimePath: "/prime-ai/ai-social-platform",
    apiPath: "/api/prime-ai/ai-social-platform/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Social / Community",
  },
  {
    id: "enterprise_ai_automation",
    title: "Enterprise AI Automation",
    slug: "enterprise-ai-automation",
    runtimePath: "/prime-ai/enterprise-ai-automation",
    apiPath: "/api/prime-ai/enterprise-ai-automation/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Enterprise Automation",
  },
  {
    id: "healthcare_medical_ai",
    title: "Healthcare & Medical AI",
    slug: "healthcare-medical-ai",
    runtimePath: "/prime-ai/healthcare-medical-ai",
    apiPath: "/api/prime-ai/healthcare-medical-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Healthcare Support",
  },
  {
    id: "ai_personal_work_marketplace",
    title: "AI Personal & Work Marketplace",
    slug: "ai-personal-work-marketplace",
    runtimePath: "/prime-ai/ai-personal-work-marketplace",
    apiPath: "/api/prime-ai/ai-personal-work-marketplace/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Productivity / Work",
  },
  {
    id: "developer_ai_ecosystem",
    title: "Developer AI Ecosystem",
    slug: "developer-ai-ecosystem",
    runtimePath: "/prime-ai/developer-ai-ecosystem",
    apiPath: "/api/prime-ai/developer-ai-ecosystem/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Developer Platform",
  },
  {
    id: "ai_business_launch_hub",
    title: "AI Business Launch Hub",
    slug: "ai-business-launch-hub",
    runtimePath: "/prime-ai/ai-business-launch-hub",
    apiPath: "/api/prime-ai/ai-business-launch-hub/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Business Launch",
  },
  {
    id: "blockchain_ai",
    title: "Blockchain AI",
    slug: "blockchain-ai",
    runtimePath: "/prime-ai/blockchain-ai",
    apiPath: "/api/prime-ai/blockchain-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Blockchain Intelligence",
  },
  {
    id: "cloud_ai",
    title: "Cloud AI",
    slug: "cloud-ai",
    runtimePath: "/prime-ai/cloud-ai",
    apiPath: "/api/prime-ai/cloud-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Cloud / DevOps",
  },
  {
    id: "telecom_ai",
    title: "Telecom AI",
    slug: "telecom-ai",
    runtimePath: "/prime-ai/telecom-ai",
    apiPath: "/api/prime-ai/telecom-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Telecom",
  },
  {
    id: "data_science_machine_learning_ai",
    title: "Data Science & Machine Learning AI",
    slug: "data-science-machine-learning-ai",
    runtimePath: "/prime-ai/data-science-machine-learning-ai",
    apiPath: "/api/prime-ai/data-science-machine-learning-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Data Science / ML",
  },
  {
    id: "legal_ai",
    title: "Legal AI",
    slug: "legal-ai",
    runtimePath: "/prime-ai/legal-ai",
    apiPath: "/api/prime-ai/legal-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Legal Support",
  },
  {
    id: "medical_ai",
    title: "Clinical Documentation & Medical Research Support AI",
    slug: "medical-ai",
    runtimePath: "/prime-ai/medical-ai",
    apiPath: "/api/prime-ai/medical-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Clinical Documentation / Research",
  },
  {
    id: "complex_project_manager_ai",
    title: "Complex Project Manager AI",
    slug: "complex-project-manager-ai",
    runtimePath: "/prime-ai/complex-project-manager-ai",
    apiPath: "/api/prime-ai/complex-project-manager-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Project Command",
  },
  {
    id: "code_software_developer_ai",
    title: "Code & Software Developer AI",
    slug: "code-software-developer-ai",
    runtimePath: "/prime-ai/code-software-developer-ai",
    apiPath: "/api/prime-ai/code-software-developer-ai/deep-runtime",
    status: "nexus_ready_not_connected",
    category: "Software Engineering",
  },
];

export const PRIME_AI_NEXUS_REGISTRY_VERSION = "prime_ai_nexus_registry_v1";
export const PRIME_AI_NEXUS_EXPECTED_COUNT = 22;
