import {
  getPumpLifecycleIntelligence,
  type PumpLifecycleInput,
} from "../lib/pump/pump-lifecycle-intelligence";

type Scenario = {
  name: string;
  input: PumpLifecycleInput;
};

const scenarios: Scenario[] = [
  {
    name: "01_empty_draft_no_indexed_data",
    input: {
      indexerReady: false,
    },
  },
  {
    name: "02_bonding_curve_started_partial_raise",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 25,
      bondingCurveRaisedStableEquivalent: 16_250,
      tradeCount: 40,
      buyCount: 30,
      sellCount: 10,
      uniqueBuyers: 25,
      marketCapUsd: 75_000,
      indexerReady: true,
    },
  },
  {
    name: "03_bonding_curve_near_graduation",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 92,
      bondingCurveRaisedStableEquivalent: 59_800,
      tradeCount: 220,
      buyCount: 160,
      sellCount: 60,
      uniqueBuyers: 120,
      marketCapUsd: 180_000,
      liquidityUsd: 25_000,
      indexerReady: true,
    },
  },
  {
    name: "04_graduation_threshold_reached_no_lp_seed",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      tradeCount: 300,
      buyCount: 210,
      sellCount: 90,
      uniqueBuyers: 220,
      marketCapUsd: 250_000,
      marketCapSustainDays250k: 3,
      indexerReady: true,
    },
  },
  {
    name: "05_graduated_lp_seeded_lp_proof_missing",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      liquiditySeeded: true,
      liquiditySeedStableEquivalent: 15_000,
      lpBurnedOrDeadWalleted: false,
      tradeCount: 400,
      buyCount: 290,
      sellCount: 110,
      uniqueBuyers: 240,
      marketCapUsd: 260_000,
      marketCapSustainDays250k: 3,
      liquidityUsd: 45_000,
      indexerReady: true,
    },
  },
  {
    name: "06_reward_stage_one_eligible",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      liquiditySeeded: true,
      liquiditySeedStableEquivalent: 15_000,
      lpBurnedOrDeadWalleted: true,
      tradeCount: 500,
      buyCount: 360,
      sellCount: 140,
      uniqueBuyers: 220,
      marketCapUsd: 260_000,
      marketCapSustainDays250k: 3,
      liquidityUsd: 70_000,
      holderCount: 260,
      topHolderConcentrationPercent: 20,
      suspiciousVolumeRatio: 0.05,
      sniperScore: 0.1,
      walletClusterRiskScore: 0.1,
      creatorSelfBuyRiskScore: 0.02,
      indexerReady: true,
    },
  },
  {
    name: "07_reward_stage_two_eligible",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      liquiditySeeded: true,
      liquiditySeedStableEquivalent: 15_000,
      lpBurnedOrDeadWalleted: true,
      tradeCount: 800,
      buyCount: 570,
      sellCount: 230,
      uniqueBuyers: 280,
      marketCapUsd: 520_000,
      marketCapSustainDays250k: 3,
      marketCapSustainDays500k: 4,
      liquidityUsd: 90_000,
      holderCount: 420,
      topHolderConcentrationPercent: 18,
      suspiciousVolumeRatio: 0.04,
      sniperScore: 0.08,
      walletClusterRiskScore: 0.08,
      creatorSelfBuyRiskScore: 0.02,
      indexerReady: true,
    },
  },
  {
    name: "08_reward_stage_three_eligible",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      liquiditySeeded: true,
      liquiditySeedStableEquivalent: 15_000,
      lpBurnedOrDeadWalleted: true,
      tradeCount: 1_050,
      buyCount: 760,
      sellCount: 290,
      uniqueBuyers: 650,
      marketCapUsd: 1_050_000,
      marketCapSustainDays250k: 3,
      marketCapSustainDays500k: 4,
      marketCapSustainDays1m: 4,
      liquidityUsd: 120_000,
      holderCount: 900,
      topHolderConcentrationPercent: 16,
      suspiciousVolumeRatio: 0.03,
      sniperScore: 0.05,
      walletClusterRiskScore: 0.07,
      creatorSelfBuyRiskScore: 0.01,
      indexerReady: true,
    },
  },
  {
    name: "09_reward_blocked_by_risk",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      liquiditySeeded: true,
      liquiditySeedStableEquivalent: 15_000,
      lpBurnedOrDeadWalleted: true,
      tradeCount: 1_200,
      buyCount: 900,
      sellCount: 300,
      uniqueBuyers: 700,
      marketCapUsd: 1_100_000,
      marketCapSustainDays250k: 3,
      marketCapSustainDays500k: 4,
      marketCapSustainDays1m: 4,
      liquidityUsd: 140_000,
      holderCount: 950,
      topHolderConcentrationPercent: 48,
      suspiciousVolumeRatio: 0.35,
      sniperScore: 0.48,
      walletClusterRiskScore: 0.5,
      creatorSelfBuyRiskScore: 0.3,
      indexerReady: true,
    },
  },
  {
    name: "10_paid_stage_flags",
    input: {
      bondingCurveLive: true,
      bondingCurveProgressPercent: 100,
      bondingCurveRaisedStableEquivalent: 65_000,
      graduationThresholdReached: true,
      liquiditySeeded: true,
      liquiditySeedStableEquivalent: 15_000,
      lpBurnedOrDeadWalleted: true,
      tradeCount: 1_100,
      buyCount: 770,
      sellCount: 330,
      uniqueBuyers: 650,
      marketCapUsd: 1_050_000,
      marketCapSustainDays250k: 3,
      marketCapSustainDays500k: 4,
      marketCapSustainDays1m: 4,
      liquidityUsd: 120_000,
      holderCount: 900,
      topHolderConcentrationPercent: 16,
      suspiciousVolumeRatio: 0.03,
      sniperScore: 0.05,
      walletClusterRiskScore: 0.07,
      creatorSelfBuyRiskScore: 0.01,
      rewardStageOnePaid: true,
      rewardStageTwoPaid: true,
      rewardStageThreePaid: true,
      indexerReady: true,
    },
  },
];

function summarize(name: string, input: PumpLifecycleInput) {
  const result = getPumpLifecycleIntelligence(input);

  return {
    name,
    phase: result.phase,
    stage: result.stage,
    title: result.title,
    nextAction: result.nextAction,
    bondingCurve: {
      status: result.bondingCurve.tradingStatus,
      progressPercent: result.bondingCurve.progressPercent,
      raised: result.bondingCurve.raisedStableEquivalent,
      remainingToGraduation: result.bondingCurve.remainingToGraduationStableEquivalent,
      trades: result.bondingCurve.tradeCount,
      buyers: result.bondingCurve.uniqueBuyers,
    },
    graduation: {
      pending: result.graduation.pending,
      liquiditySeeded: result.graduation.liquiditySeeded,
      liquiditySeed: result.graduation.liquiditySeedStableEquivalent,
      lpProof: result.graduation.lpBurnedOrDeadWalleted,
    },
    health: {
      total: result.health.total,
      liquidityStability: result.health.liquidityStability,
      holderDistribution: result.health.holderDistribution,
      organicVolume: result.health.organicVolume,
      lowBotActivity: result.health.lowBotActivity,
      marketCapSustainability: result.health.marketCapSustainability,
      explanation: result.health.explanation,
    },
    economics: {
      remainingAfterSeed: result.rewards.remainingAfterSeedStableEquivalent,
      creatorRewardReserve: result.rewards.creatorRewardReserveStableEquivalent,
      ecosystemReserve: result.rewards.ecosystemDevelopmentReserveStableEquivalent,
      totalConfiguredRewardPercent: result.rewards.totalConfiguredRewardPercent,
    },
    rewards: result.rewards.stages.map((stage) => ({
      id: stage.id,
      label: stage.label,
      eligible: stage.eligible,
      paid: stage.paid,
      blocked: stage.blocked,
      milestoneMarketCapUsd: stage.milestoneMarketCapUsd,
      sustainDays: stage.sustainDays,
      rewardPercent: stage.rewardPercentOfRemainingFunds,
      reason: stage.reason,
    })),
    riskFlags: result.riskFlags,
    indexerRequirements: result.indexerRequirements,
  };
}

const output = scenarios.map((scenario) => summarize(scenario.name, scenario.input));

console.log(JSON.stringify(output, null, 2));
